export const extToLanguage: { [ext: string]: string } = {
  '.py': 'python',
  '.js': 'javascript',
  '.jsx': 'javascript',
  '.ts': 'typescript',
  '.tsx': 'typescript',
  '.java': 'java',
  '.cs': 'csharp',
  '.go': 'go',
  '.rb': 'ruby',
  '.php': 'php',
  '.rs': 'rust',
  '.cpp': 'cpp',
  '.c': 'c',
  '.kt': 'kotlin',
  '.scala': 'scala',
  '.swift': 'swift',
  '.hs': 'haskell',
}
