/*
 * THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 *
 * Run `npx ets` or `yarn ets` to regenerate this file.
 * Source: ./chatPlanner2.ets
 */
/* eslint-disable */

interface Props {
  message: string;
  thought: string;
  toolResults: string[];
}

export default function (props: Props): string {
  let result = "";
  result += "User's request: ";
  result += props.message;
  result += "\n\nYour previous thought:\n";
  result += props.thought;
  result += "\n\nHere are the results of the tools you invoked:\n";
  result += props.toolResults.join("\n\n");
  result += "\n\n------------\n\nYour response to the user, in Markdown:";
  return result;
}
