/*
 * THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 *
 * Run `npx ets` or `yarn ets` to regenerate this file.
 * Source: ./chatPlanner1.ets
 */
/* eslint-disable */

interface Props {
  message: string;
  references: string[];
  tools: string[];
}

export default function (props: Props): string {
  let result = "";
  result += props.references.join("\n\n");
  result += "\n=======\nUser's request: ";
  result += props.message;
  result +=
    '\n\n======\n\nThink step by step to come up with a thoughtful response. \n- if you need to clarify the request, feel free to ask for it\n- if certain API information is missing / outdated, you may want to search the internet\n- if there are common follow-up questions, you may want to answer them\n\nOutput Format:\n\nTHOUGHT: your current thought on the request\nTOOLS: [ { "name": "name of tool", "input": ["args"] } ]\n\nOr if you need help:\n\nTHOUGHT: I need clarification\n<question to ask the user goes here>\n\nOr if you can answer the request:\n\nTHOUGHT: I can answer this\n<answer goes here>\n\nAlways return JSON for the tools section, and Markdown for text for the user.\n\nYour output:';
  return result;
}
