/*
 * THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 *
 * Run `npx ets` or `yarn ets` to regenerate this file.
 * Source: ./chatPilot.ets
 */
/* eslint-disable */

interface Props {
  request: string;
  references: string;
}

export default function (props: Props): string {
  let result = "";
  result += props.references;
  result += "\n\nBased on my query + previous history, answer the question:\n";
  result += props.request;
  result += "\n";
  return result;
}
