/*
 * THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 *
 * Run `npx ets` or `yarn ets` to regenerate this file.
 * Source: ./draftPilot.ets
 */
/* eslint-disable */

interface Props {
  message: string;
  references: string | undefined;
  exampleJson: string;
}

export default function (props: Props): string {
  let result = "";
  result += props.references;
  result += "\n=======\nUser's request: ";
  result += props.message;
  result +=
    "\n\nThink step by step to come up with a plan of action. You can output one of the following:\n\n1. Research\nDescription: Request more information from the user.\nWhen to use: API is unknown (implement a NextJS 13 router), or too vague (implement a backend)\nOutput Format: \n   RESEARCH: <short summary of request>\n   All the questions you need for the user to provide to get to a clear plan\n\n2. User Action\nDescription: Propose a way for the user to implement the request themselves.\nWhen to use: big refactors (e.g. replace x with y everywhere), moves (rename folder x to y), 5+ files to edit\nOutput Format: \n  SUGGESTION: <short summary of request>\n  How the user could implement the request themselves, e.g. with unix tools or their IDE\n  \n3. Action Plan\nDescription: Provide a plan of action for the user's request that will be executed by AI\nWhen to use: when you know what to do\nOutput Format:\n  PLAN: <3-6 word summary of the request>\n  the steps in markdown\n  a '---' separator\n  the list of files to modify (with full paths) and how they should be changed in this format:\n  - path/to/file.tsx - add a row of buttons under the main <div>\n  - other/path/style.css - add a new class called .my-class\n  (do not output actual code but include any context needed for an agent to make the change like \n  paths to other files, actual urls, etc. do not make reference to previous chat messages):\n  a '---' separator\n  confidence: low or high\n  - high = the user's request was clear and straightforward, there's not much room for interpretation\n  - low = the user's request was vague, i had to make up a lot of implementation details\n\nAlways follow this format. Your output:";
  return result;
}
