/*
 * THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 *
 * Run `npx ets` or `yarn ets` to regenerate this file.
 * Source: ./editPilot.ets
 */
/* eslint-disable */

interface Props {
  message: string;
  files: string;
  exampleJson: string;
}

export default function (props: Props): string {
  let result = "";
  result +=
    "Given the request in the prior messages, make the requested changes using the JSON operation format\ndescribed. If there are no edits to make, don't include that file. New files will be created.\n\nHere is a list of files.\n";
  result += props.files;
  result +=
    '\n\n---\nThis example shows all possible operations & thier inputs: ${props.exampleJson}\n\nYour return format is a JSON object with files as keys and arrays of operations as values:\n{\n  "path/to/file": [edit operations],\n  "path/to/newfile": [insertion operation],\n  ...\n}\n\nResponse JSON:';
  return result;
}
