/*
 * THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 *
 * Run `npx ets` or `yarn ets` to regenerate this file.
 * Source: ./editPilot.ets
 */
/* eslint-disable */

interface Props {
  message: string;
  attachments?: string;
}

export default function (props: Props): string {
  let result = "";
  result += props.attachments;
  result +=
    '\nGiven the request in the prior messages, come up with a list of files to create or modify and the changes to make to them. If you need some specific details, you can ask for it, otherwise reply in this exact JSON format:\n\n{\n  "path/to/file": "detailed list of changes to make so an AI can understand",\n  "path/to/bigchange": "! if the changes are large/complex (e.g. 10+ lines of code), add ! at the beginning"\n  ...\n}\n\nThe JSON output should ONLY contain string values.\n\nJSON Change Plan or question to ask the user: ';
  result += props.message;
  return result;
}
