/*
 * THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 *
 * Run `npx ets` or `yarn ets` to regenerate this file.
 * Source: ./fileEditor.ets
 */
/* eslint-disable */

interface Props {
  file: string;
  plan: string;
  changes: string;
  contents: string;
  exampleJson: string;
  outputFullFile: boolean;
}

export default function (props: Props): string {
  let result = "";
  result += "You are given the following plan: ";
  result += props.plan;
  result += "\n\nNow editing: ";
  result += props.file;
  result += "\nChanges to make: ";
  result += props.changes;
  result += "\n---\n\n";
  result += props.contents;
  result += "\n\n---\n\n";
  result += props.outputFullFile
    ? "Output the entire file that I will write to disk, only changing the requested lines, and no markdown like ```:"
    : `---

You return a sequence of operations in JSON. This example shows all possible operations & thier
inputs: ${props.exampleJson}

JSON array of operations to perform:`;
  return result;
}
