/*
 * THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 *
 * Run `npx ets` or `yarn ets` to regenerate this file.
 * Source: ./genContext.ets
 */
/* eslint-disable */

interface Props {
  manifest: string;
  folders: string;
  referenceCode: string;
}

export default function (props: Props): string {
  let result = "";
  result += "selected code snippets:\n";
  result += props.referenceCode;
  result += "\n\n---\n";
  result += props.manifest;
  result += "\n\n---\nkey folders:\n";
  result += props.folders;
  result +=
    "\n\n---\nPlease generate ~3 paragraphs describing the key libraries and code patterns in use in this project so an AI can generate code that fits in. Do not evaulate whether anything is good or bad, just describe the interesting facts to an AI language model.\n\nHere is an example:\nThis is a react & express project. The frontend uses tailwindcss and lives in src/react. The backend uses nodejs and express and lives in src/server. Database is sqlite3 and defined in src/db. Business logic lives in src/directors.\n\nThe frontend store logic is using a library called nanostores, which exposes an `atom<type>` helper with .set and .get methods. In the ui components. `useStore(atomVariable)` is used to get access to the variable.\n\n---\nProject context:";
  return result;
}
