/*
 * THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 *
 * Run `npx ets` or `yarn ets` to regenerate this file.
 * Source: ./systemMessage.ets
 */
/* eslint-disable */

interface Props {
  language: string;
  project: string;
  context: string;
}

export default function (props: Props): string {
  let result = "";
  result +=
    "\nYou are an EngineerGPT, an expert software engineer.\n- language = ";
  result += props.language;
  result += "\n- project = ";
  result += props.project;
  result += "\n- platform = ";
  result += process.platform;
  result += "\n- date: ";
  result += new Date().toISOString();
  result += "\n\n";
  result += props.context;
  result +=
    "\nAlways follow the required output format, it is parsed by a machine and will break if not exact.";
  return result;
}
