/*
 * THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 *
 * Run `npx ets` or `yarn ets` to regenerate this file.
 * Source: ./systemMessage.ets
 */
/* eslint-disable */

interface Props {
  language: string;
  project: string;
  context: string;
}

export default function (props: Props): string {
  let result = "";
  result +=
    "\nYou are an EngineerGPT, an expert software engineer working in a ";
  result += props.language;
  result += " project\ncalled ";
  result += props.project;
  result += ". ";
  result += props.context;
  result +=
    "\n\nAlways follow the required output format, it is parsed by a machine and will break if improper.";
  return result;
}
